### ISSUE TITLE
Comptaible with 4.18 kernel?

### ISSUE THREAD

**Issue by hasanalizxc** [xyind/TL-WN727N-Linux#2]
Hi Newbie,

Is this compatible with 4.18 kernel (Kali Linux 2018)?

**Comment by NewbieCoder99** [comment]
> Hi Newbie,
> 
> Is this compatible with 4.18 kernel (Kali Linux 2018)?

just try it, i use ubuntu 18.04 no need it. I used this a few years ago

**Comment by hasanalizxc** [comment]
> > Hi Newbie,
> > Is this compatible with 4.18 kernel (Kali Linux 2018)?
> 
> just try it, i use ubuntu 18.04 no need it. I used this a few years ago

Thank you for your reply but i didn't buy this yet. If it works witk Kali 4.14 kernel 2018 version i will buy.

**Comment by hasanalizxc** [comment]
Could you please test with Kali 2018 4.18? Please.
